apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nsu6cbmvs-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nsu6cbmvs-python 
  name: nsu6cbmvs-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nsu6cbmvs-python 
