apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nsu6cbmvs-python 
  janus-idp.io/tekton: nsu6cbmvs-python
  backstage.io/kubernetes-id: nsu6cbmvs-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nsu6cbmvs-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml